### ISSUE TITLE
Issues with FullManager get

### ISSUE THREAD

**Issue by Loonride** [sjyk/deeplens-cv#25] opened 2020-04-05 19:30 UTC
I know the API is constantly changing, but the way I was previously using put and get with FullManager doesn't seem to be working anymore (I made some slight changes for the new `put` args). Anything I am doing wrong below? I get a video returned back, but it seems to have no frames.

```python
from deeplens.struct import *
from deeplens.utils import *
from deeplens.dataflow.map import *
from deeplens.full_manager.full_manager import *
from deeplens.full_manager.condition import Condition
from deeplens.full_manager.full_video_processing import CropSplitter
from deeplens.tracking.background import FixedCameraBGFGSegmenter
from experiments.environ import *
from deeplens.utils.testing_utils import *

def do_filter(conn, video_name):
    c = conn.cursor()
    c.execute("SELECT clip_id FROM clip WHERE video_name = '%s'" % (video_name))
    res = c.fetchall()
    print(res)
    return [cl[0] for cl in res]

manager = FullStorageManager(CustomTagger(FixedCameraBGFGSegmenter().segment, batch_size=100), CropSplitter(), 'test_store')
manager.put('test.mp4', 'test1', {'frame_rate': 30, 'encoding': XVID, 'limit': -1, 'sample': 1.0, 'offset': 0, 'batch_size': 100, 'num_processes': 1, 'background_scale': 1}, False, False)

res = manager.get('test1', Condition(label='foreground', custom_filter=do_filter))
vid = res[0]
# doesn't print anything because there are no frames
for frame in vid:
    print('frame')
# doesn't play anything:
play(vid)
```

**Comment by swjz** [comment] 2020-04-06 04:42
It's weird that I can't reproduce the bug you described - I'm running the code you provided but everything seems to be just fine. Could you make sure that you're on the **master** branch? We have recently merged all commits from integrate branch to master and to avoid confusion, I've deleted the old integrate branch from GitHub. If the issue persists, could you please check the followings: (1) What's inside the `vid` variable - is it empty? (2) Do you have anything in your `test_store` folder? If you have `header.db` in it, could you check if it's an empty sqlite database? If you have several video clips in the folder, do they match what you have in `header.db`? Thanks!

**Comment by swjz** [comment] 2020-04-06 04:46
Also I've set up GitHub Actions and the latest commit from master branch seems to be working (https://github.com/sjyk/deeplens-cv/runs/557662969). It would be great if you could also try to reproduce that test case (https://github.com/sjyk/deeplens-cv/blob/master/tests/test_tagger.py) yourself!

**Comment by Loonride** [comment] 2020-04-06 04:51
My mistake, I didn't realize that we are back to using `master`. I saw that `integrate` was gone and saw that there were recent commits on the `feedback` branch so I went to that. I will check if it is working for me on master.

**Comment by Loonride** [comment] 2020-04-06 05:23
Everything works for me on master, sorry for the mistake!

**Comment by swjz** [comment] 2020-04-06 05:25
It's okay, glad it works!

**Closed by swjz** 2020-04-06 05:25 UTC
